[[pages]]
path = "/"
screenshotTimestamp = "2026-03-29T04:52:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/694a832b-9163-45fb-8aaf-8391337cf9ae/6b82a884-0d41-44ed-80f6-b8aba89d734d/0CisiGi"

[[pages]]
path = "/spaces"
screenshotTimestamp = "2026-03-29T04:52:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/694a832b-9163-45fb-8aaf-8391337cf9ae/6b82a884-0d41-44ed-80f6-b8aba89d734d/j5Hc6bi"

[[pages]]
path = "/items"
screenshotTimestamp = "2026-03-29T05:50:06Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/694a832b-9163-45fb-8aaf-8391337cf9ae/6b82a884-0d41-44ed-80f6-b8aba89d734d/g8eK99q"
